/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-2",
    "aws_appsync_graphqlEndpoint": "https://t6eungj7dvfmvlnmm34rhncfxe.appsync-api.eu-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "eu-west-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-2wyaxfq6tjexfhxsm4qb6gxqg4",
    "aws_cognito_identity_pool_id": "eu-west-2:cbba7159-1b08-4151-aa20-5b5cbd0d93e1",
    "aws_cognito_region": "eu-west-2",
    "aws_user_pools_id": "eu-west-2_URwsem56Z",
    "aws_user_pools_web_client_id": "4hir9fo13ql4s69ptrah0u61d8",
    "oauth": {
        "domain": "edgebacktesting89b302ad-89b302ad-dev.auth.eu-west-2.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "http://localhost:3000/",
        "redirectSignOut": "http://localhost:3000/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS"
};


export default awsmobile;
